### ISSUE TITLE
01-xmlrpc-client.t hangs on Windows

### ISSUE THREAD

**Issue by chorny** [OpusVL/OpenERP-XMLRPC-Simple#2]
```
ok 1 - use OpenERP::XMLRPC::Client;
# Running mock server on port 9000
ok 2 - created
ok 3 - has the method "object_execute"
ok 4 - has the method "object_exec_workflow"
ok 5 - has the method "report_report"
ok 6 - has the method "report_report_get"
1..6
(hangs)
```

**Comment by colinnewell** [comment]
The test failures appear to be test library specific rather than a fundamental problem with the module.  Testing against an external OpenERP server works correctly.  I think I will have to skip those tests on windows as fixing them is more work than it's worth for me right now.

The libraries are almost certainly fork related of some nature.  It should technically be possible to fix, but I don't see a simple way to do it.

**Comment by colinnewell** [comment]
The module should now pass it's tests on Windows, although this obviously isn't an ideal fix.
